# Time-stamp: <07/01/23 14:12:04 ptr>
#
# Copyright (c) 2006
# Petr Ovtchenkov
#
# Licensed under the Academic Free License version 3.0
#

SRCROOT := ..
SUBDIRS := mt sockios stem misc

include ${SRCROOT}/Makefiles/gmake/subdirs.mak

all install depend clean clobber distclean check:
	$(doinsubdirs)

.PHONY: all install depend clean clobber distclean check
