# -*- Makefile -*- Time-stamp: <05/03/28 22:43:09 ptr>
# $Id$

SRCROOT := ../../
COMPILER_NAME := gcc

include Makefile.inc
include ${SRCROOT}/Makefiles/top.mak


INCLUDES += -I$(STLPORT_INCLUDE_DIR)


