# -*- Makefile -*- Time-stamp: <09/03/26 01:30:54 ptr>

LIBNAME = xmt
MAJOR = 2
MINOR = 0
PATCH = 13
SRC_CC = xmt.cc thr_mgr.cc time.cc uid.cc shm.cc callstack.cc system_error.cc thread.cc \
         date_time.cc lfstream.cc
