# -*- Makefile -*- Time-stamp: <09/05/08 11:04:23 ptr>

LIBNAME = xmt
MAJOR = 2
MINOR = 1
PATCH = 1
SRC_CC = xmt.cc thr_mgr.cc time.cc uid.cc shm.cc callstack.cc system_error.cc thread.cc \
         date_time.cc lfstream.cc
