# -*- Makefile -*- Time-stamp: <08/12/19 20:22:04 yeti>

LIBNAME = xmt
MAJOR = 2
MINOR = 0
PATCH = 11
SRC_CC = xmt.cc thr_mgr.cc time.cc uid.cc shm.cc callstack.cc system_error.cc thread.cc \
         date_time.cc lfstream.cc
