# -*- Makefile -*- Time-stamp: <08/04/23 09:49:02 ptr>

SRCROOT := ../../..

include Makefile.inc
include ${SRCROOT}/Makefiles/gmake/top.mak

INCLUDES += -I$(SRCROOT)/include -I$(BOOST_INCLUDE_DIR)



