# -*- Makefile -*- Time-stamp: <05/12/27 01:05:58 ptr>

SRCROOT := ../../../../..
COMPILER_NAME := gcc
WITHOUT_STLPORT := 1

ALL_TAGS := release-shared


USE_STDLIB := yes

include ../Makefile.inc
include ${SRCROOT}/Makefiles/gmake/top.mak
