# -*- Makefile -*- Time-stamp: <03/03/21 11:58:08 ptr>

LIBNAME = testx1
LIBNAMES = testx1x testx2
MAJOR = .0
MINOR = .1
PATCH = .0
SRC_CPP = testx1.cpp

testx1x_SRC_CPP = testx1.cpp
testx2_SRC_CPP = testx2.cpp
