# -*- Makefile -*-

PRGNAME = ut_intercessor
SRC_CC = unit_test.cc \
         dummy_srv.cc \
         ../http.cc \
         ../intercessor.cc \
         ../server.cc \
         http_test.cc \
         intercessor_test.cc \
         intercessor_test_suite.cc         
