# -*- Makefile -*- Time-stamp: <05/10/03 22:50:40 ptr>

SRCROOT := ../..
COMPILER_NAME := gcc

include Makefile.inc
include ${SRCROOT}/Makefiles/top.mak

INCLUDES += -I$(SRCROOT)/include

dbg-shared: DEFS += -D__DEBUG

LDLIBS += -ldl

