# -*- makefile -*- Time-stamp: <09/06/05 00:22:34 ptr>

PRGNAME = stem_ut
SRC_CC = unit_test.cc \
         Node.cc \
         NameService.cc \
         Echo.cc \
         Convert.cc \
         Cron.cc \
         vf.cc
