# -*- Makefile -*- Time-stamp: <03/07/09 18:08:47 ptr>
# $Id$

DIRS = add add-ropes find find-ropes ops ops-ropes params params-ropes params-ref params-ref-ropes

all:
	for d in $(DIRS); do \
	  (cd $$d; make); \
	done

