# -*- Makefile -*- Time-stamp: <06/01/04 00:30:48 ptr>

SRCROOT := ../../../../..
COMPILER_NAME := gcc

ALL_TAGS := release-shared

STLPORT_DIR := /export/home/ptr/STLport.lab/STLport
STLPORT_LIB_DIR := ../../../build/lib

include ../Makefile2.inc
include ${SRCROOT}/Makefiles/top.mak
