# -*- makefile -*- Time-stamp: <07/07/18 08:37:31 ptr>

PRGNAME = sockios_ut
SRC_CC = ConnectionProcessor.cc message.cc client-mw.cc \
         client-wc.cc close_socket.cc bytes_in_socket.cc bytes_in_socket2.cc \
         names.cc sockios_test.cc sockios_test_suite.cc unit_test.cc
