# -*- makefile -*- Time-stamp: <02/09/03 20:38:40 ptr>
# $Id$

BASEDIR := $(shell xtmp=`pwd`; xtmp=`dirname $$xtmp`; xtmp=`dirname $$xtmp`; dirname $$xtmp)
COMPILER_NAME = gcc

include ./Makefile.inc

all:	release-shared

all-shared:	release-shared dbg-shared stldbg-shared

all-debug:	dbg-shared stldbg-shared

all-release:	release-shared

include ${BASEDIR}/Makefiles/app/Makefile.inc

INCLUDES += -I$(STLPORT_INCLUDE_DIR)

BUILD_SYSTEM := $(shell echo "`uname -n` `uname -s` `uname -r` `uname -v` `uname -p`")
BUILD_DATE := $(shell echo "`date +'%Y/%m/%d %T %Z'`")

ifeq ($(OS_VER),SunOS)
LDLIBS = 
else
LDLIBS = 
endif

LDLIBS += -lrt -lnsl

ifeq ($(OS_VER),SunOS)
dbg-shared:	LDFLAGS += -L${INSTALL_LIB_DIR_DBG}
stldbg-shared:	LDFLAGS += -L${INSTALL_LIB_DIR_STLDBG}
release-shared:	LDFLAGS += -L${INSTALL_LIB_DIR}
endif

ifeq ($(OS_VER),Linux)
release-shared:	LDFLAGS += -L${STLPORT_LIB_DIR} -L${INSTALL_LIB_DIR}
stldbg-shared:	LDFLAGS += -L${STLPORT_LIB_DIR} -L${INSTALL_LIB_DIR_STLDBG}
dbg-shared:	LDFLAGS += -L${STLPORT_LIB_DIR} -L${INSTALL_LIB_DIR_DBG}
endif

dbg-shared : LDLIBS += \
                    -lstlport_gcc -lxmt_gcc-g

stldbg-shared : LDLIBS += \
                    -lstlport_gcc_stldebug -lxmt_gcc_stl-g

release-shared : LDLIBS += \
                    -lstlport_gcc -lxmt_gcc

test-release-shared:	release-shared
	@(export LD_LIBRARY_PATH=$$LD_LIBRARY_PATH:${BASEDIR}/build/lib; \
	  $(OUTPUT_DIR)/${PRGNAME} || { echo "${PRGNAME} fail"; exit 1; } )
	@echo "${PRGNAME} ok"

$(OUTPUT_DIR)/version.o:	version.c version.h FORCE
	$(COMPILE.c) $(OUTPUT_OPTION) \
	  -DBUILD_SYSTEM="\"${BUILD_SYSTEM}\"" \
	  -DBUILD_DATE="\"${BUILD_DATE}\"" -DKEYWORD="\"${KEYWORD}\"" \
	  -DMAJOR=${MAJOR} -DMINOR=${MINOR} -DPATCH=${PATCH} version.c

$(OUTPUT_DIR_DBG)/version.o:	version.c version.h FORCE
	$(COMPILE.c) $(OUTPUT_OPTION) \
	  -DBUILD_SYSTEM="\"${BUILD_SYSTEM}\"" \
	  -DBUILD_DATE="\"${BUILD_DATE}\"" -DKEYWORD="\"${KEYWORD}\"" \
	  -DMAJOR=${MAJOR} -DMINOR=${MINOR} -DPATCH=${PATCH} version.c

$(OUTPUT_DIR_STLDBG)/version.o:	version.c version.h FORCE
	$(COMPILE.c) $(OUTPUT_OPTION) \
	  -DBUILD_SYSTEM="\"${BUILD_SYSTEM}\"" \
	  -DBUILD_DATE="\"${BUILD_DATE}\"" -DKEYWORD="\"${KEYWORD}\"" \
	  -DMAJOR=${MAJOR} -DMINOR=${MINOR} -DPATCH=${PATCH} version.c

FORCE:

