# -*- makefile -*- Time-stamp: <02/12/02 12:49:02 ptr>

SRCROOT := ../../..
COMPILER_NAME := gcc

include Makefile.inc
include ${SRCROOT}/Makefiles/gmake/top.mak

INCLUDES +=
DEFS += 

ifeq ($(OS_VER),SunOS)
LDLIBS = -lrt
endif

FORCE:

