# -*- Makefile -*-

PRGNAME = ut_vtime

SRC_CC = unit_test.cc \
         vt_operations.cc \
         OneGroup.cc \
         OneGroup-State.cc \
         OneGroup-State-Recover.cc \
         leader.cc
