# -*- Makefile -*-

PRGNAME = ut_vtime

SRC_CC = unit_test.cc \
         vt_operations.cc \
         OneGroup.cc \
         OneGroup-State.cc

#         vt_object.cc \
#         vt_dispatch.cc \
#         vt_handler.cc \
#         vt_remote
