# -*- Makefile -*- Time-stamp: <05/12/31 00:11:40 ptr>

SRCROOT := ../../../../..
COMPILER_NAME := gcc
WITHOUT_STLPORT := 1

ALL_TAGS := release-shared


include ../Makefile.inc
include ${SRCROOT}/Makefiles/gmake/top.mak

