# -*- Makefile -*- Time-stamp: <06/11/30 16:51:10 ptr>

LIBNAME = stem
MAJOR = 4
MINOR = 4
PATCH = 0
SRC_CC = _EventHandler.cc NetTransport.cc EvManager.cc EvPack.cc crc.cc \
         Names.cc Cron.cc

