# -*- Makefile -*- Time-stamp: <07/03/12 20:19:19 ptr>

LIBNAME = stem
MAJOR = 4
MINOR = 5
PATCH = 0
SRC_CC = _EventHandler.cc NetTransport.cc EvManager.cc EvPack.cc crc.cc \
         Names.cc Cron.cc

