# -*- Makefile -*- Time-stamp: <08/07/08 13:13:44 yeti>

LIBNAME = stem
MAJOR = 4
MINOR = 8
PATCH = 2
SRC_CC = _EventHandler.cc NetTransport.cc EvManager.cc EvPack.cc crc.cc \
         Names.cc Cron.cc
