# -*- Makefile -*- Time-stamp: <08/07/02 09:28:02 ptr>

LIBNAME = xmt
MAJOR = 2
MINOR = 0
PATCH = 5
SRC_CC = xmt.cc thr_mgr.cc time.cc uid.cc shm.cc callstack.cc system_error.cc thread.cc \
         date_time.cc
SRC_C = fl.c
