# -*- Makefile -*- Time-stamp: <08/06/30 13:51:45 yeti>

LIBNAME = xmt
MAJOR = 2
MINOR = 0
PATCH = 4
SRC_CC = xmt.cc thr_mgr.cc time.cc uid.cc shm.cc callstack.cc system_error.cc thread.cc \
         date_time.cc
SRC_C = fl.c
