# -*- Makefile -*- Time-stamp: <08/07/25 10:25:30 ptr>

LIBNAME = xmt
MAJOR = 2
MINOR = 0
PATCH = 8
SRC_CC = xmt.cc thr_mgr.cc time.cc uid.cc shm.cc callstack.cc system_error.cc thread.cc \
         date_time.cc
SRC_C = fl.c
