# -*- Makefile -*- Time-stamp: <04/01/09 16:53:50 ptr>
# $Id$

SRCROOT := ../../..
COMPILER_NAME := gcc

include Makefile.inc
include ${SRCROOT}/Makefiles/top.mak

DEFS += -D_GNU_SOURCE

LDFLAGS += -ldl

