# -*- Makefile -*- Time-stamp: <05/12/27 00:54:52 ptr>

SRCROOT := ../../../../..
COMPILER_NAME := gcc
WITHOUT_STLPORT := 1

ALL_TAGS := release-shared


include ../Makefile.inc
include ${SRCROOT}/Makefiles/gmake/top.mak
