# -*- makefile -*- Time-stamp: <06/12/18 16:43:21 ptr>

PRGNAME = sockios_ut
SRC_CC = unit_test.cc ConnectionProcessor.cc message.cc client.cc client-mw.cc \
         client-wc.cc close_socket.cc bytes_in_socket.cc bytes_in_socket2.cc read0_on_exec.cc \
         sockios_test.cc sockios_test_suite.cc
