# -*- Makefile -*- Time-stamp: <07/07/05 09:31:15 ptr>

SRCROOT := ../../..

include Makefile.inc
include ${SRCROOT}/Makefiles/gmake/top.mak

# INCLUDES += -I${BOOST_DIR}
INCLUDES += -I${CoMT_INCLUDE_DIR}
DEFS += -D__FIT_EXAM

LDFLAGS += -Wl,-rpath=${STLPORT_LIB_DIR}
