# -*- makefile -*- Time-stamp: <06/12/16 00:37:10 ptr>

PRGNAME = mt_ut
SRC_CC = unit_test.cc timespec.cc mutex_test.cc spinlock_test.cc \
         recursive_mutex.cc join.cc signal-1.cc signal-2.cc signal-3.cc flck.cc lfs.cc \
         mt_test.cc mt_test_suite.cc
