# -*- makefile -*- Time-stamp: <07/02/06 10:04:25 ptr>

PRGNAME = mt_ut
SRC_CC = unit_test.cc timespec.cc \
         signal-1.cc signal-2.cc signal-3.cc flck.cc lfs.cc \
         mt_test.cc mt_test_suite.cc
