# -*- Makefile -*- Time-stamp: <03/07/09 18:08:47 ptr>
# $Id$

SRCROOT := ../../..
COMPILER_NAME := gcc

ALL_TAGS := release-shared dbg-shared

include Makefile.inc
include ${SRCROOT}/Makefiles/gmake/top.mak

