# -*- makefile -*- Time-stamp: <03/09/17 11:07:49 ptr>
# $Id: Makefile.inc,v 1.1 2003/10/06 08:01:06 ptr Exp $

PRGNAME = tecol_ut
SRC_CC = ../ConnectionProcessor.cc client.cc message.cc unit_test.cc
