# -*- makefile -*- Time-stamp: <06/07/17 10:27:56 ptr>

PRGNAME = sockios_ut
SRC_CC = unit_test.cc ConnectionProcessor.cc message.cc client.cc client-mw.cc \
         client-wc.cc close_socket.cc bytes_in_socket.cc
