# -*- makefile -*- Time-stamp: <02/09/03 21:03:57 ptr>
# $Id$

BASEDIR := $(shell xtmp=`pwd`; xtmp=`dirname $$xtmp`; xtmp=`dirname $$xtmp`; xtmp=`dirname $$xtmp`; dirname $$xtmp)
COMPILER_NAME = gcc

include ./Makefile.inc

all:	release-shared

all-shared:	release-shared dbg-shared stldbg-shared

all-debug:	dbg-shared stldbg-shared

all-release:	release-shared

include ${BASEDIR}/Makefiles/app/Makefile.inc

INCLUDES += -I$(STLPORT_INCLUDE_DIR)

BUILD_SYSTEM := $(shell echo "`uname -n` `uname -s` `uname -r` `uname -v` `uname -p`")
BUILD_DATE := $(shell echo "`date +'%Y/%m/%d %T %Z'`")

ifeq ($(OS_VER),SunOS)
LDLIBS = 
else
LDLIBS = 
endif

LDLIBS += -lrt -lnsl

ifeq ($(OS_VER),SunOS)
dbg-shared:	LDFLAGS += -L${INSTALL_LIB_DIR_DBG}
stldbg-shared:	LDFLAGS += -L${INSTALL_LIB_DIR_STLDBG}
release-shared:	LDFLAGS += -L${INSTALL_LIB_DIR}
endif

ifeq ($(OS_VER),Linux)
release-shared:	LDFLAGS += -L${STLPORT_LIB_DIR} -L${INSTALL_LIB_DIR}
stldbg-shared:	LDFLAGS += -L${STLPORT_LIB_DIR} -L${INSTALL_LIB_DIR_STLDBG}
dbg-shared:	LDFLAGS += -L${STLPORT_LIB_DIR} -L${INSTALL_LIB_DIR_DBG}
endif

dbg-shared : LDLIBS += \
                    -lstlport_gcc -lxmt_${COMPILER_NAME}${DBG_SUFFIX} \
		    -lDB_${COMPILER_NAME}${DBG_SUFFIX}

stldbg-shared : LDLIBS += \
                    -lstlport_gcc_stldebug -lxmt_${COMPILER_NAME}_stl${DBG_SUFFIX} \
		    -lDB_${COMPILER_NAME}_stl${DBG_SUFFIX}

release-shared : LDLIBS += \
                    -lstlport_gcc -lxmt_${COMPILER_NAME} \
		    -lDB_${COMPILER_NAME}

FORCE:

