# -*- Makefile -*- Time-stamp: <06/01/04 00:22:44 ptr>

SRCROOT := ../../../../..
COMPILER_NAME := gcc

ALL_TAGS := release-shared

STLPORT_LIB_DIR := ../../../build/lib

include ../Makefile3.inc
include ${SRCROOT}/Makefiles/top.mak
