# -*- Makefile -*- Time-stamp: <05/11/17 00:13:10 ptr>

SRCROOT := ../..
COMPILER_NAME := gcc

include Makefile.inc
include ${SRCROOT}/Makefiles/top.mak

INCLUDES += -I.. -I$(BOOST_INCLUDE_DIR)

LIBS += -lresolv
