# -*- Makefile -*- Time-stamp: <08/04/23 10:17:12 ptr>

SRCROOT := ../../../..

include Makefile.inc
include ${SRCROOT}/Makefiles/gmake/top.mak

INCLUDES += -I$(SRCROOT)/include -I$(BOOST_INCLUDE_DIR) -I..
