# -*- Makefile -*- Time-stamp: <03/07/09 18:08:47 ptr>

SRCROOT := ../../..
COMPILER_NAME := gcc

#STLPORT_DIR := /export/home/ptr/STLport.lab/STLport-Makefiles
include Makefile.inc
include ${SRCROOT}/Makefiles/top.mak
