# -*- Makefile -*- Time-stamp: <05/10/03 22:50:40 ptr>

SRCROOT := ../..

include Makefile.inc
include ${SRCROOT}/Makefiles/gmake/top.mak

INCLUDES += -I$(SRCROOT)/include

dbg-shared: DEFS += -D__DEBUG

LDLIBS += -ldl
