# -*- makefile -*- Time-stamp: <07/07/19 00:16:55 ptr>

PRGNAME = sockios_ut
SRC_CC = ConnectionProcessor.cc message.cc \
         bytes_in_socket.cc bytes_in_socket2.cc \
         names.cc sockios_test.cc sockios_test_suite.cc unit_test.cc
