# Time-stamp: <08/01/08 15:20:25 ptr>
#
# Copyright (c) 2007,2008
# Petr Ovtchenkov
#
# Licensed under the Academic Free License version 3.0
#

SRCROOT := ../../../..

PDFNAMES = ExamUseCaseSpec

ExamUseCaseSpec_SRC_TEX = ExamUseCaseSpec.tex
ExamUseCaseSpec_SRC_FIG = p1.fig p2.fig p3.fig p4.fig p5.fig debug-focus.fig

include $(SRCROOT)/Makefiles/gmake/topdoc.mak
