# -*- makefile -*- Time-stamp: <08/03/26 10:12:36 ptr>

PRGNAME = mt_ut
SRC_CC = unit_test.cc timespec.cc \
         signal-1.cc signal-3.cc \
         mt_test.cc shm_test.cc mt_test_suite.cc \
         mt_test_wg21.cc
