# -*- makefile -*- Time-stamp: <09/03/13 15:41:49 ptr>

PRGNAME = mt_ut
SRC_CC = sys_err_test.cc timespec.cc \
         signal-1.cc signal-3.cc \
         shm_test.cc mt_test_suite.cc \
         mt_test_wg21.cc flock_test.cc
