# -*- Makefile -*- Time-stamp: <04/01/09 16:53:50 ptr>
# $Id: Makefile 1356 2006-11-01 13:34:19Z complement $

SRCROOT := ../../..
COMPILER_NAME := gcc

include Makefile.inc
include ${SRCROOT}/Makefiles/gmake/top.mak

DEFS += -D_GNU_SOURCE

LDFLAGS += -ldl

