# -*- Makefile -*- Time-stamp: <03/07/09 18:08:47 ptr>
# $Id$

SRCROOT := ../../..
COMPILER_NAME := gcc
WITHOUT_STLPORT := 1

#STLPORT_DIR := /export/home/ptr/STLport.lab/cvs.stlport.com/STLport
include Makefile.inc
include ${SRCROOT}/Makefiles/gmake/top.mak


#DEFS += -D_STLP_LEAKS_PEDANTIC

#LDFLAGS += -Wl,-rpath=$(STLPORT_LIB_DIR)

#release-shared:	LDSEARCH = -L${STLPORT_LIB_DIR}
#stldbg-shared:	LDSEARCH = -L${STLPORT_LIB_DIR}
#dbg-shared:	LDSEARCH = -L${STLPORT_LIB_DIR}

