# -*- makefile -*- Time-stamp: <08/02/15 22:36:40 ptr>

PRGNAME = mt_ut
SRC_CC = unit_test.cc timespec.cc \
         signal-1.cc signal-3.cc \
         mt_test.cc mt_test_suite.cc \
         mt_test_wg21.cc
