# -*- makefile -*- Time-stamp: <08/07/02 09:03:03 ptr>

PRGNAME = mt_ut
SRC_CC = timespec.cc \
         signal-1.cc signal-3.cc \
         mt_test.cc shm_test.cc mt_test_suite.cc \
         mt_test_wg21.cc
