# -*- makefile -*- Time-stamp: <04/01/13 15:53:28 ptr>
# $Id$

LIBNAME = flck
MAJOR = 0
MINOR = 1
PATCH = 0
SRC_CPP = fl.cpp
# SRC_CPP = ${BOOST_TST_SRC}/execution_monitor.cpp ${BOOST_TST_SRC}/test_tools.cpp \
#          ${BOOST_TST_SRC}/unit_test_parameters.cpp \
#          ${BOOST_TST_SRC}/unit_test_log.cpp ${BOOST_TST_SRC}/unit_test_monitor.cpp \
#          ${BOOST_TST_SRC}/unit_test_result.cpp \
#          ${BOOST_TST_SRC}/unit_test_suite.cpp ${BOOST_TST_SRC}/unit_test_main.cpp
