# -*- Makefile -*- Time-stamp: <03/07/09 18:08:47 ptr>

SRCROOT := ../../..
COMPILER_NAME := gcc
STLPORT_DIR := /export/home/ptr/STLport.lab/STLport.5_0

include Makefile.inc
include ${SRCROOT}/Makefiles/gmake/top.mak


LDFLAGS += -Wl,-rpath=$(STLPORT_LIB_DIR)
