# -*- makefile -*- Time-stamp: <04/05/06 18:40:56 ptr>
# $Id$

PRGNAME = mt_ut
SRC_CC = unit_test.cc timespec.cc mutex_test.cc spinlock_test.cc \
		 recursive_mutex.cc join.cc signal-1.cc signal-2.cc flck.cc lfs.cc
