# Time-stamp: <99/12/17 14:21:44 ptr>
# $SunId$ %Q%

default:	libdbg_so

libdbg_so:
	?(cd obj.${COMPILER_NAME}; make)

clear:
	?(cd obj.${COMPILER_NAME}; make clear)

clear-all:
	?(cd obj.${COMPILER_NAME}; make clear-all)
