# -*- Makefile -*- Time-stamp: <10/05/19 17:04:44 ptr>

LIBNAME = stem
MAJOR = 5
MINOR = 4
PATCH = 3
SRC_CC = _EventHandler.cc NetTransport.cc EvManager.cc EvPack.cc crc.cc \
         Names.cc Cron.cc
