# -*- Makefile -*- Time-stamp: <10/01/18 20:23:59 ptr>

LIBNAME = stem
MAJOR = 5
MINOR = 3
PATCH = 6
SRC_CC = _EventHandler.cc NetTransport.cc EvManager.cc EvPack.cc crc.cc \
         Names.cc Cron.cc
