# -*- Makefile -*- Time-stamp: <10/05/25 11:58:58 ptr>

LIBNAME = stem
MAJOR = 5
MINOR = 4
PATCH = 6
SRC_CC = _EventHandler.cc NetTransport.cc EvManager.cc EvPack.cc crc.cc \
         Names.cc Cron.cc
